# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Files/Code/Python/Raytracer GUI/ui/dialog_yn.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 150)
        Dialog.setMinimumSize(QtCore.QSize(250, 150))
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropshadow_frame = QtWidgets.QFrame(Dialog)
        self.dropshadow_frame.setMinimumSize(QtCore.QSize(230, 130))
        self.dropshadow_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius: 20px;\n"
"}")
        self.dropshadow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropshadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropshadow_frame.setObjectName("dropshadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dropshadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.dropshadow_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(221, 51, 34);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.description = QtWidgets.QLabel(self.dropshadow_frame)
        self.description.setMinimumSize(QtCore.QSize(0, 40))
        self.description.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.description.setFont(font)
        self.description.setStyleSheet("color: #aaaaaa;")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout_2.addWidget(self.description)
        self.btn_frame = QtWidgets.QFrame(self.dropshadow_frame)
        self.btn_frame.setMinimumSize(QtCore.QSize(230, 40))
        self.btn_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_frame.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(39, 39, 39);")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.btn_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.btn_frame)
        self.buttonBox.setMinimumSize(QtCore.QSize(230, 40))
        self.buttonBox.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBox.setFont(font)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStyleSheet("QPushButton{\n"
"background-color: rgb(221, 51, 34);\n"
"border-radius: 13px;\n"
"min-width: 50px;\n"
"min-height: 20px;\n"
"padding: 3px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 85, 68);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid rgb(48, 48, 48)\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.btn_frame)
        self.verticalLayout.addWidget(self.dropshadow_frame)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "Title"))
        self.description.setText(_translate("Dialog", "Short Message Description for Clarity"))
