# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Files/Code/Python/RtGUI/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 600)
        Settings.setStyleSheet("QLineEdit{\n"
"    color: rgb(221, 221, 221);\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;\n"
"    selection-color: rgb(16, 16, 16);\n"
"    selection-background-color: rgb(221, 51, 34);\n"
"}\n"
"QLineEdit::focus{\n"
"    border-color: rgb(221, 51, 34);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(Settings)
        self.drop_shadow_frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: #151515;\n"
"    border-radius: 10px;\n"
"}")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMinimumSize(QtCore.QSize(380, 0))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("QFrame{\n"
"    background-color: #303030;\n"
"    border-radius: 10px;\n"
"}")
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(self.title_bar)
        self.title.setMinimumSize(QtCore.QSize(0, 50))
        self.title.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel{\n"
"    background-color: none;\n"
"    color: #dd3322;\n"
"    padding-left: 50px;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exitSettingsBtn = QtWidgets.QPushButton(self.frame_btns)
        self.exitSettingsBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.exitSettingsBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.exitSettingsBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Files/Code/Python/RtGUI/ui\\../exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitSettingsBtn.setIcon(icon)
        self.exitSettingsBtn.setIconSize(QtCore.QSize(14, 14))
        self.exitSettingsBtn.setObjectName("exitSettingsBtn")
        self.horizontalLayout_2.addWidget(self.exitSettingsBtn)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_3.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("QLabel{\n"
"    background-color: none;\n"
"    color: #dd3322;\n"
"    font-family: Segoe UI;    \n"
"}")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.content_bar)
        self.frame_3.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: #202020;\n"
"    border-radius: 10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 300, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: none;\n"
"    color: #dd3322;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.width = QtWidgets.QLineEdit(self.frame_3)
        self.width.setGeometry(QtCore.QRect(120, 80, 95, 20))
        self.width.setMaximumSize(QtCore.QSize(95, 16777215))
        self.width.setAlignment(QtCore.Qt.AlignCenter)
        self.width.setObjectName("width")
        self.height = QtWidgets.QLineEdit(self.frame_3)
        self.height.setGeometry(QtCore.QRect(220, 80, 95, 20))
        self.height.setMaximumSize(QtCore.QSize(95, 16777215))
        self.height.setAlignment(QtCore.Qt.AlignCenter)
        self.height.setObjectName("height")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 110, 200, 20))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 87, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 87, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 140, 51, 20))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(95, 16777215))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.content_bar)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: #202020;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(30, 10, 30, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.reflection_depth = QtWidgets.QLineEdit(self.frame_2)
        self.reflection_depth.setMaximumSize(QtCore.QSize(200, 16777215))
        self.reflection_depth.setAlignment(QtCore.Qt.AlignCenter)
        self.reflection_depth.setObjectName("reflection_depth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reflection_depth)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    background-color: none;\n"
"    color: #dd3322;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.content_bar)
        self.verticalLayout.addWidget(self.drop_shadow_frame)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.title.setText(_translate("Settings", "SETTINGS"))
        self.label_4.setText(_translate("Settings", "CAMERA SETTINGS"))
        self.width.setText(_translate("Settings", "1920"))
        self.width.setPlaceholderText(_translate("Settings", "Width"))
        self.height.setText(_translate("Settings", "1080"))
        self.height.setPlaceholderText(_translate("Settings", "Height"))
        self.label_5.setText(_translate("Settings", "Width x Height"))
        self.label_6.setText(_translate("Settings", "Environment"))
        self.label_2.setText(_translate("Settings", "Reflection Depth"))
        self.reflection_depth.setText(_translate("Settings", "5"))
        self.label_3.setText(_translate("Settings", "Min Displace"))
        self.lineEdit_2.setText(_translate("Settings", "0.0001"))
        self.label.setText(_translate("Settings", "ENGINE SETTINGS"))
