# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Files/Code/Python/RtGUI/ui/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))
        MainWindow.setMaximumSize(QtCore.QSize(880, 16777215))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color: rgb(221, 51, 34);\n"
"    color: rgb(29, 29, 29);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 68);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 1px solid rgb(32, 32, 32);\n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"    color: rgb(221, 221, 221);\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;\n"
"    selection-color: rgb(16, 16, 16);\n"
"    selection-background-color: rgb(221, 51, 34);\n"
"}\n"
"QLineEdit::focus{\n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QToolTip{\n"
"    background-color: rgb(26, 26, 26);\n"
"    color: rgb(170, 170, 170);\n"
"    border: 1px solid rgb(50,50,50);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(32,32,32);\n"
"    border-radius: 10px;\n"
"}")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setEnabled(True)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_bar.setStyleSheet("QFrame{\n"
"background-color: none;\n"
"}")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 9)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(221, 51, 34);\n"
"background-color: none;")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_4.addWidget(self.label_title)
        self.openbtn = QtWidgets.QPushButton(self.frame_title)
        self.openbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.openbtn.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openbtn.setFont(font)
        self.openbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.openbtn.setToolTip("")
        self.openbtn.setStyleSheet("")
        self.openbtn.setObjectName("openbtn")
        self.horizontalLayout_4.addWidget(self.openbtn)
        self.savebtn = QtWidgets.QPushButton(self.frame_title)
        self.savebtn.setMinimumSize(QtCore.QSize(0, 20))
        self.savebtn.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.savebtn.setFont(font)
        self.savebtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.savebtn.setStyleSheet("")
        self.savebtn.setObjectName("savebtn")
        self.horizontalLayout_4.addWidget(self.savebtn)
        self.path_label = QtWidgets.QLabel(self.frame_title)
        self.path_label.setMinimumSize(QtCore.QSize(271, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.path_label.setFont(font)
        self.path_label.setStyleSheet("color: rgb(170, 170, 170);")
        self.path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.path_label.setObjectName("path_label")
        self.horizontalLayout_4.addWidget(self.path_label)
        self.settingsbtn = QtWidgets.QPushButton(self.frame_title)
        self.settingsbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.settingsbtn.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.settingsbtn.setFont(font)
        self.settingsbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingsbtn.setObjectName("settingsbtn")
        self.horizontalLayout_4.addWidget(self.settingsbtn)
        self.renderbtn = QtWidgets.QPushButton(self.frame_title)
        self.renderbtn.setMinimumSize(QtCore.QSize(0, 20))
        self.renderbtn.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.renderbtn.setFont(font)
        self.renderbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.renderbtn.setObjectName("renderbtn")
        self.horizontalLayout_4.addWidget(self.renderbtn)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(66, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setContentsMargins(10, 9, 10, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_minimize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_minimize.setToolTip("")
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Files/Code/Python/RtGUI/ui\\../minimize.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setIconSize(QtCore.QSize(14, 14))
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_close.setToolTip("")
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Files/Code/Python/RtGUI/ui\\../exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setIconSize(QtCore.QSize(14, 14))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("QFrame {\n"
"background-color: rgb(28,28,28);\n"
"}\n"
"\n"
"")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.content_bar)
        self.gridLayout.setObjectName("gridLayout")
        self.material_properties = QtWidgets.QFrame(self.content_bar)
        self.material_properties.setMinimumSize(QtCore.QSize(0, 367))
        self.material_properties.setMaximumSize(QtCore.QSize(16777215, 376))
        self.material_properties.setStyleSheet("QFrame{\n"
"    background-color: rgb(39, 39, 39);\n"
"}")
        self.material_properties.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.material_properties.setFrameShadow(QtWidgets.QFrame.Raised)
        self.material_properties.setObjectName("material_properties")
        self.matlabel = QtWidgets.QLabel(self.material_properties)
        self.matlabel.setGeometry(QtCore.QRect(9, 9, 401, 21))
        self.matlabel.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.matlabel.setFont(font)
        self.matlabel.setStyleSheet("color: rgb(221, 51, 34);\n"
"")
        self.matlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.matlabel.setObjectName("matlabel")
        self.mat_entryfields = QtWidgets.QFrame(self.material_properties)
        self.mat_entryfields.setGeometry(QtCore.QRect(9, 36, 400, 331))
        self.mat_entryfields.setMinimumSize(QtCore.QSize(0, 0))
        self.mat_entryfields.setStyleSheet("QLabel{\n"
"    background-color: none;\n"
"    color: rgb(221, 51, 34);\n"
"    font-family: Segoe UI;\n"
"}")
        self.mat_entryfields.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mat_entryfields.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mat_entryfields.setObjectName("mat_entryfields")
        self.matname = QtWidgets.QLineEdit(self.mat_entryfields)
        self.matname.setGeometry(QtCore.QRect(10, 20, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.matname.setFont(font)
        self.matname.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.matname.setStyleSheet("")
        self.matname.setText("")
        self.matname.setAlignment(QtCore.Qt.AlignCenter)
        self.matname.setPlaceholderText("")
        self.matname.setObjectName("matname")
        self.difz = QtWidgets.QLineEdit(self.mat_entryfields)
        self.difz.setGeometry(QtCore.QRect(190, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.difz.setFont(font)
        self.difz.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.difz.setStyleSheet("")
        self.difz.setText("")
        self.difz.setAlignment(QtCore.Qt.AlignCenter)
        self.difz.setObjectName("difz")
        self.difx = QtWidgets.QLineEdit(self.mat_entryfields)
        self.difx.setGeometry(QtCore.QRect(10, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.difx.setFont(font)
        self.difx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.difx.setStyleSheet("")
        self.difx.setText("")
        self.difx.setAlignment(QtCore.Qt.AlignCenter)
        self.difx.setObjectName("difx")
        self.dify = QtWidgets.QLineEdit(self.mat_entryfields)
        self.dify.setGeometry(QtCore.QRect(100, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dify.setFont(font)
        self.dify.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dify.setStyleSheet("")
        self.dify.setText("")
        self.dify.setAlignment(QtCore.Qt.AlignCenter)
        self.dify.setObjectName("dify")
        self.diffusemap = QtWidgets.QPushButton(self.mat_entryfields)
        self.diffusemap.setGeometry(QtCore.QRect(340, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diffusemap.setFont(font)
        self.diffusemap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.diffusemap.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.diffusemap.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/Files/Code/Python/RtGUI/ui\\../texture.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("D:/Files/Code/Python/RtGUI/ui\\../textureh.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.diffusemap.setIcon(icon2)
        self.diffusemap.setIconSize(QtCore.QSize(22, 22))
        self.diffusemap.setCheckable(True)
        self.diffusemap.setFlat(False)
        self.diffusemap.setObjectName("diffusemap")
        self.specularmap = QtWidgets.QPushButton(self.mat_entryfields)
        self.specularmap.setGeometry(QtCore.QRect(340, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.specularmap.setFont(font)
        self.specularmap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.specularmap.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.specularmap.setText("")
        self.specularmap.setIcon(icon2)
        self.specularmap.setIconSize(QtCore.QSize(22, 22))
        self.specularmap.setCheckable(True)
        self.specularmap.setObjectName("specularmap")
        self.specz = QtWidgets.QLineEdit(self.mat_entryfields)
        self.specz.setGeometry(QtCore.QRect(190, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.specz.setFont(font)
        self.specz.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.specz.setStyleSheet("")
        self.specz.setText("")
        self.specz.setAlignment(QtCore.Qt.AlignCenter)
        self.specz.setObjectName("specz")
        self.specx = QtWidgets.QLineEdit(self.mat_entryfields)
        self.specx.setGeometry(QtCore.QRect(10, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.specx.setFont(font)
        self.specx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.specx.setStyleSheet("")
        self.specx.setText("")
        self.specx.setAlignment(QtCore.Qt.AlignCenter)
        self.specx.setObjectName("specx")
        self.specy = QtWidgets.QLineEdit(self.mat_entryfields)
        self.specy.setGeometry(QtCore.QRect(100, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.specy.setFont(font)
        self.specy.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.specy.setStyleSheet("")
        self.specy.setText("")
        self.specy.setAlignment(QtCore.Qt.AlignCenter)
        self.specy.setObjectName("specy")
        self.emisz = QtWidgets.QLineEdit(self.mat_entryfields)
        self.emisz.setGeometry(QtCore.QRect(190, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.emisz.setFont(font)
        self.emisz.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.emisz.setStyleSheet("")
        self.emisz.setText("")
        self.emisz.setAlignment(QtCore.Qt.AlignCenter)
        self.emisz.setObjectName("emisz")
        self.emisy = QtWidgets.QLineEdit(self.mat_entryfields)
        self.emisy.setGeometry(QtCore.QRect(100, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.emisy.setFont(font)
        self.emisy.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.emisy.setStyleSheet("")
        self.emisy.setText("")
        self.emisy.setAlignment(QtCore.Qt.AlignCenter)
        self.emisy.setObjectName("emisy")
        self.emisx = QtWidgets.QLineEdit(self.mat_entryfields)
        self.emisx.setGeometry(QtCore.QRect(10, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.emisx.setFont(font)
        self.emisx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.emisx.setStyleSheet("")
        self.emisx.setText("")
        self.emisx.setAlignment(QtCore.Qt.AlignCenter)
        self.emisx.setObjectName("emisx")
        self.reflectivity = QtWidgets.QLineEdit(self.mat_entryfields)
        self.reflectivity.setGeometry(QtCore.QRect(10, 170, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.reflectivity.setFont(font)
        self.reflectivity.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reflectivity.setStyleSheet("")
        self.reflectivity.setText("")
        self.reflectivity.setAlignment(QtCore.Qt.AlignCenter)
        self.reflectivity.setPlaceholderText("")
        self.reflectivity.setObjectName("reflectivity")
        self.matname_label = QtWidgets.QLabel(self.mat_entryfields)
        self.matname_label.setGeometry(QtCore.QRect(20, 0, 361, 20))
        self.matname_label.setObjectName("matname_label")
        self.diffuse_label = QtWidgets.QLabel(self.mat_entryfields)
        self.diffuse_label.setGeometry(QtCore.QRect(20, 50, 361, 20))
        self.diffuse_label.setObjectName("diffuse_label")
        self.specular_label = QtWidgets.QLabel(self.mat_entryfields)
        self.specular_label.setGeometry(QtCore.QRect(20, 100, 361, 20))
        self.specular_label.setObjectName("specular_label")
        self.reflectivity_label = QtWidgets.QLabel(self.mat_entryfields)
        self.reflectivity_label.setGeometry(QtCore.QRect(20, 150, 361, 20))
        self.reflectivity_label.setObjectName("reflectivity_label")
        self.emission_label = QtWidgets.QLabel(self.mat_entryfields)
        self.emission_label.setGeometry(QtCore.QRect(20, 200, 361, 20))
        self.emission_label.setObjectName("emission_label")
        self.normalmap = QtWidgets.QPushButton(self.mat_entryfields)
        self.normalmap.setGeometry(QtCore.QRect(340, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.normalmap.setFont(font)
        self.normalmap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.normalmap.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.normalmap.setText("")
        self.normalmap.setIcon(icon2)
        self.normalmap.setIconSize(QtCore.QSize(22, 22))
        self.normalmap.setCheckable(True)
        self.normalmap.setObjectName("normalmap")
        self.normal_label = QtWidgets.QLabel(self.mat_entryfields)
        self.normal_label.setGeometry(QtCore.QRect(20, 250, 361, 20))
        self.normal_label.setObjectName("normal_label")
        self.normalstrength = QtWidgets.QLineEdit(self.mat_entryfields)
        self.normalstrength.setGeometry(QtCore.QRect(10, 270, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.normalstrength.setFont(font)
        self.normalstrength.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.normalstrength.setStyleSheet("")
        self.normalstrength.setText("")
        self.normalstrength.setAlignment(QtCore.Qt.AlignCenter)
        self.normalstrength.setPlaceholderText("")
        self.normalstrength.setObjectName("normalstrength")
        self.diffusevis = QtWidgets.QPushButton(self.mat_entryfields)
        self.diffusevis.setGeometry(QtCore.QRect(280, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.diffusevis.setFont(font)
        self.diffusevis.setFocusPolicy(QtCore.Qt.NoFocus)
        self.diffusevis.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: #000000;\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.diffusevis.setFlat(False)
        self.diffusevis.setObjectName("diffusevis")
        self.specularvis = QtWidgets.QPushButton(self.mat_entryfields)
        self.specularvis.setGeometry(QtCore.QRect(280, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.specularvis.setFont(font)
        self.specularvis.setFocusPolicy(QtCore.Qt.NoFocus)
        self.specularvis.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: #000000;\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.specularvis.setFlat(False)
        self.specularvis.setObjectName("specularvis")
        self.emissionvis = QtWidgets.QPushButton(self.mat_entryfields)
        self.emissionvis.setGeometry(QtCore.QRect(280, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emissionvis.setFont(font)
        self.emissionvis.setFocusPolicy(QtCore.Qt.NoFocus)
        self.emissionvis.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(64, 64, 64);\n"
"    border-radius: 10px;    \n"
"    background-color: #000;\n"
"}\n"
"QPushButton:hover {    \n"
"    border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    border-color: rgb(255, 102, 85);\n"
"}\n"
"QPushButton:checked{    \n"
"    border-color: rgb(96, 221, 33);\n"
"}")
        self.emissionvis.setFlat(False)
        self.emissionvis.setObjectName("emissionvis")
        self.applymat = QtWidgets.QPushButton(self.material_properties)
        self.applymat.setGeometry(QtCore.QRect(170, 350, 80, 20))
        self.applymat.setMinimumSize(QtCore.QSize(80, 20))
        self.applymat.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.applymat.setFont(font)
        self.applymat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.applymat.setStyleSheet("")
        self.applymat.setObjectName("applymat")
        self.gridLayout.addWidget(self.material_properties, 0, 1, 1, 1)
        self.object_list_frame = QtWidgets.QFrame(self.content_bar)
        self.object_list_frame.setMaximumSize(QtCore.QSize(418, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.object_list_frame.setFont(font)
        self.object_list_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.object_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.object_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.object_list_frame.setObjectName("object_list_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.object_list_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addobj = QtWidgets.QPushButton(self.object_list_frame)
        self.addobj.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addobj.setFont(font)
        self.addobj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addobj.setStyleSheet("")
        self.addobj.setObjectName("addobj")
        self.gridLayout_2.addWidget(self.addobj, 0, 0, 1, 1)
        self.delobj = QtWidgets.QPushButton(self.object_list_frame)
        self.delobj.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.delobj.setFont(font)
        self.delobj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delobj.setStyleSheet("")
        self.delobj.setObjectName("delobj")
        self.gridLayout_2.addWidget(self.delobj, 1, 0, 1, 1)
        self.obj_list = QtWidgets.QListWidget(self.object_list_frame)
        self.obj_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.obj_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.obj_list.setStyleSheet("QListWidget{\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(170, 170, 170);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #dd3322;\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"\n"
"QListWidget::item\n"
"{\n"
"margin-top: 0px;\n"
"    margin-bottom: 3px;\n"
"    margin-left: 0px;\n"
"    margin-right: 3px;\n"
"    padding: 5px;\n"
"    background: #1a1a1a;\n"
"    border-radius: 13px;\n"
"border: none;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: #dd3322;\n"
"    color: #101010;\n"
"    border: none;\n"
"    padding: 5px\n"
"}\n"
"QListWidget::item:hover\n"
"{\n"
"    background: #505050;\n"
"    color: #101010;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 5px;\n"
"    margin-left: 2px;\n"
"    margin-right: 5px;\n"
"border-radius: 11px;\n"
"}\n"
"\n"
"")
        self.obj_list.setAlternatingRowColors(False)
        self.obj_list.setProperty("isWrapping", True)
        self.obj_list.setObjectName("obj_list")
        self.gridLayout_2.addWidget(self.obj_list, 0, 1, 3, 1)
        self.clearobj = QtWidgets.QPushButton(self.object_list_frame)
        self.clearobj.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clearobj.setFont(font)
        self.clearobj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearobj.setStyleSheet("")
        self.clearobj.setObjectName("clearobj")
        self.gridLayout_2.addWidget(self.clearobj, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.object_list_frame, 1, 0, 1, 1)
        self.object_properties = QtWidgets.QFrame(self.content_bar)
        self.object_properties.setMinimumSize(QtCore.QSize(0, 376))
        self.object_properties.setMaximumSize(QtCore.QSize(16777215, 376))
        self.object_properties.setStyleSheet("QFrame{\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.object_properties.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.object_properties.setFrameShadow(QtWidgets.QFrame.Raised)
        self.object_properties.setObjectName("object_properties")
        self.objlabel = QtWidgets.QLabel(self.object_properties)
        self.objlabel.setGeometry(QtCore.QRect(9, 9, 401, 21))
        self.objlabel.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.objlabel.setFont(font)
        self.objlabel.setStyleSheet("color: rgb(221, 51, 34);\n"
"")
        self.objlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.objlabel.setObjectName("objlabel")
        self.obj_entryfields = QtWidgets.QFrame(self.object_properties)
        self.obj_entryfields.setGeometry(QtCore.QRect(9, 36, 400, 305))
        self.obj_entryfields.setStyleSheet("QLineEdit{\n"
"color: rgb(221, 221, 221);\n"
"background-color: rgb(48, 48, 48);\n"
"border: 2px solid rgb(64, 64, 64);\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border-color: rgb(221, 51, 34);\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color: none;\n"
"    color: rgb(221, 51, 34);\n"
"    font-family: Segoe UI;\n"
"}")
        self.obj_entryfields.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.obj_entryfields.setFrameShadow(QtWidgets.QFrame.Raised)
        self.obj_entryfields.setObjectName("obj_entryfields")
        self.objname = QtWidgets.QLineEdit(self.obj_entryfields)
        self.objname.setGeometry(QtCore.QRect(10, 20, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objname.sizePolicy().hasHeightForWidth())
        self.objname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.objname.setFont(font)
        self.objname.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.objname.setStyleSheet("")
        self.objname.setText("")
        self.objname.setAlignment(QtCore.Qt.AlignCenter)
        self.objname.setPlaceholderText("")
        self.objname.setObjectName("objname")
        self.radius = QtWidgets.QLineEdit(self.obj_entryfields)
        self.radius.setGeometry(QtCore.QRect(10, 120, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.radius.setFont(font)
        self.radius.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radius.setStyleSheet("")
        self.radius.setText("")
        self.radius.setAlignment(QtCore.Qt.AlignCenter)
        self.radius.setPlaceholderText("")
        self.radius.setObjectName("radius")
        self.objmat = QtWidgets.QLineEdit(self.obj_entryfields)
        self.objmat.setGeometry(QtCore.QRect(10, 170, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.objmat.setFont(font)
        self.objmat.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.objmat.setStyleSheet("")
        self.objmat.setText("")
        self.objmat.setAlignment(QtCore.Qt.AlignCenter)
        self.objmat.setPlaceholderText("")
        self.objmat.setObjectName("objmat")
        self.posz = QtWidgets.QLineEdit(self.obj_entryfields)
        self.posz.setGeometry(QtCore.QRect(270, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.posz.setFont(font)
        self.posz.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.posz.setStyleSheet("")
        self.posz.setText("")
        self.posz.setAlignment(QtCore.Qt.AlignCenter)
        self.posz.setObjectName("posz")
        self.posx = QtWidgets.QLineEdit(self.obj_entryfields)
        self.posx.setGeometry(QtCore.QRect(10, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.posx.setFont(font)
        self.posx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.posx.setStyleSheet("")
        self.posx.setText("")
        self.posx.setAlignment(QtCore.Qt.AlignCenter)
        self.posx.setObjectName("posx")
        self.posy = QtWidgets.QLineEdit(self.obj_entryfields)
        self.posy.setGeometry(QtCore.QRect(140, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.posy.setFont(font)
        self.posy.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.posy.setStyleSheet("")
        self.posy.setText("")
        self.posy.setAlignment(QtCore.Qt.AlignCenter)
        self.posy.setObjectName("posy")
        self.material_label = QtWidgets.QLabel(self.obj_entryfields)
        self.material_label.setGeometry(QtCore.QRect(20, 150, 361, 20))
        self.material_label.setObjectName("material_label")
        self.radius_label = QtWidgets.QLabel(self.obj_entryfields)
        self.radius_label.setGeometry(QtCore.QRect(20, 100, 361, 20))
        self.radius_label.setObjectName("radius_label")
        self.position_label = QtWidgets.QLabel(self.obj_entryfields)
        self.position_label.setGeometry(QtCore.QRect(20, 50, 361, 20))
        self.position_label.setObjectName("position_label")
        self.objname_label = QtWidgets.QLabel(self.obj_entryfields)
        self.objname_label.setGeometry(QtCore.QRect(20, 0, 361, 20))
        self.objname_label.setObjectName("objname_label")
        self.applyobj = QtWidgets.QPushButton(self.object_properties)
        self.applyobj.setGeometry(QtCore.QRect(170, 350, 80, 20))
        self.applyobj.setMinimumSize(QtCore.QSize(80, 20))
        self.applyobj.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.applyobj.setFont(font)
        self.applyobj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.applyobj.setStyleSheet("")
        self.applyobj.setObjectName("applyobj")
        self.gridLayout.addWidget(self.object_properties, 0, 0, 1, 1)
        self.material_list_frame = QtWidgets.QFrame(self.content_bar)
        self.material_list_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.material_list_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(39, 39, 39);\n"
"}")
        self.material_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.material_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.material_list_frame.setObjectName("material_list_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.material_list_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addmat = QtWidgets.QPushButton(self.material_list_frame)
        self.addmat.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addmat.setFont(font)
        self.addmat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addmat.setStyleSheet("")
        self.addmat.setObjectName("addmat")
        self.gridLayout_3.addWidget(self.addmat, 0, 0, 1, 1)
        self.mat_list = QtWidgets.QListWidget(self.material_list_frame)
        self.mat_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mat_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mat_list.setStyleSheet("QListWidget{\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(170, 170, 170);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #dd3322;\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #303030;\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"\n"
"QListWidget::item\n"
"{\n"
"margin-top: 0px;\n"
"    margin-bottom: 3px;\n"
"    margin-left: 0px;\n"
"    margin-right: 3px;\n"
"    padding: 5px;\n"
"    background: #1a1a1a;\n"
"    border-radius: 13px;\n"
"border: none;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: #dd3322;\n"
"    color: #101010;\n"
"    border: none;\n"
"    padding: 5px\n"
"}\n"
"QListWidget::item:hover\n"
"{\n"
"    background: #505050;\n"
"    color: #101010;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 5px;\n"
"    margin-left: 2px;\n"
"    margin-right: 5px;\n"
"border-radius: 11px;\n"
"}\n"
"\n"
"")
        self.mat_list.setAlternatingRowColors(False)
        self.mat_list.setProperty("isWrapping", True)
        self.mat_list.setObjectName("mat_list")
        self.gridLayout_3.addWidget(self.mat_list, 0, 1, 3, 1)
        self.clearmat = QtWidgets.QPushButton(self.material_list_frame)
        self.clearmat.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clearmat.setFont(font)
        self.clearmat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearmat.setStyleSheet("")
        self.clearmat.setObjectName("clearmat")
        self.gridLayout_3.addWidget(self.clearmat, 2, 0, 1, 1)
        self.delmat = QtWidgets.QPushButton(self.material_list_frame)
        self.delmat.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.delmat.setFont(font)
        self.delmat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delmat.setStyleSheet("")
        self.delmat.setObjectName("delmat")
        self.gridLayout_3.addWidget(self.delmat, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.material_list_frame, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color: rgb(32, 32, 32);")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_label_credits)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        self.label_credits.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(80, 80, 80);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_5.addWidget(self.label_credits)
        self.frame = QtWidgets.QFrame(self.frame_label_credits)
        self.frame.setMinimumSize(QtCore.QSize(0, 28))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressViewer = QtWidgets.QFrame(self.frame)
        self.progressViewer.setGeometry(QtCore.QRect(250, 4, 20, 20))
        self.progressViewer.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.24581 rgba(0, 0, 0, 0), stop:0.399 rgba(0, 0, 0, 0), stop:0.4 rgba(221, 51, 34, 255));\n"
"border-radius: 10px;")
        self.progressViewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressViewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressViewer.setObjectName("progressViewer")
        self.horizontalLayout_5.addWidget(self.frame)
        self.label_status = QtWidgets.QLabel(self.frame_label_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(80, 28))
        self.label_status.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: rgb(221, 51, 34);")
        self.label_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_5.addWidget(self.label_status)
        self.progressBar = QtWidgets.QProgressBar(self.frame_label_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"color: #aaaaaa;\n"
"margin: 5px;\n"
"background-color: #303030;\n"
"border: none;\n"
"border-radius: 9\n"
"}\n"
"\n"
"QProgressBar:chunk{\n"
"background-color: #dd3322;\n"
"border: none;\n"
"border-radius: 9;\n"
"}")
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.horizontalLayout_2.addWidget(self.frame_label_credits, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.objname, self.posx)
        MainWindow.setTabOrder(self.posx, self.posy)
        MainWindow.setTabOrder(self.posy, self.posz)
        MainWindow.setTabOrder(self.posz, self.radius)
        MainWindow.setTabOrder(self.radius, self.objmat)
        MainWindow.setTabOrder(self.objmat, self.matname)
        MainWindow.setTabOrder(self.matname, self.difx)
        MainWindow.setTabOrder(self.difx, self.dify)
        MainWindow.setTabOrder(self.dify, self.difz)
        MainWindow.setTabOrder(self.difz, self.specx)
        MainWindow.setTabOrder(self.specx, self.specy)
        MainWindow.setTabOrder(self.specy, self.specz)
        MainWindow.setTabOrder(self.specz, self.reflectivity)
        MainWindow.setTabOrder(self.reflectivity, self.emisx)
        MainWindow.setTabOrder(self.emisx, self.emisy)
        MainWindow.setTabOrder(self.emisy, self.emisz)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SCENE</span> EDITOR</p></body></html>"))
        self.openbtn.setText(_translate("MainWindow", "OPEN"))
        self.openbtn.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.savebtn.setText(_translate("MainWindow", "SAVE"))
        self.savebtn.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.path_label.setText(_translate("MainWindow", "new_scene.sc"))
        self.settingsbtn.setText(_translate("MainWindow", "SETTINGS"))
        self.settingsbtn.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.renderbtn.setText(_translate("MainWindow", "RENDER"))
        self.renderbtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.matlabel.setText(_translate("MainWindow", "<strong>MATERIALS</strong>"))
        self.difz.setPlaceholderText(_translate("MainWindow", "B"))
        self.difx.setPlaceholderText(_translate("MainWindow", "R"))
        self.dify.setPlaceholderText(_translate("MainWindow", "G"))
        self.specz.setPlaceholderText(_translate("MainWindow", "B"))
        self.specx.setPlaceholderText(_translate("MainWindow", "R"))
        self.specy.setPlaceholderText(_translate("MainWindow", "G"))
        self.emisz.setPlaceholderText(_translate("MainWindow", "B"))
        self.emisy.setPlaceholderText(_translate("MainWindow", "G"))
        self.emisx.setPlaceholderText(_translate("MainWindow", "R"))
        self.matname_label.setText(_translate("MainWindow", "Material Name"))
        self.diffuse_label.setText(_translate("MainWindow", "Diffuse"))
        self.specular_label.setText(_translate("MainWindow", "Specular"))
        self.reflectivity_label.setText(_translate("MainWindow", "Reflectivity"))
        self.emission_label.setText(_translate("MainWindow", "Emission"))
        self.normal_label.setText(_translate("MainWindow", "Normal"))
        self.applymat.setText(_translate("MainWindow", "APPLY"))
        self.applymat.setShortcut(_translate("MainWindow", "Return"))
        self.addobj.setText(_translate("MainWindow", "ADD"))
        self.addobj.setShortcut(_translate("MainWindow", "Alt+O"))
        self.delobj.setText(_translate("MainWindow", "DEL"))
        self.delobj.setShortcut(_translate("MainWindow", "Backspace, Del"))
        self.clearobj.setText(_translate("MainWindow", "CLEAR"))
        self.objlabel.setText(_translate("MainWindow", "<strong>OBJECTS</strong>"))
        self.posz.setPlaceholderText(_translate("MainWindow", "Z"))
        self.posx.setPlaceholderText(_translate("MainWindow", "X"))
        self.posy.setPlaceholderText(_translate("MainWindow", "Y"))
        self.material_label.setText(_translate("MainWindow", "Material"))
        self.radius_label.setText(_translate("MainWindow", "Radius"))
        self.position_label.setText(_translate("MainWindow", "Position"))
        self.objname_label.setText(_translate("MainWindow", "Object Name"))
        self.applyobj.setText(_translate("MainWindow", "APPLY"))
        self.applyobj.setShortcut(_translate("MainWindow", "Return"))
        self.addmat.setText(_translate("MainWindow", "ADD"))
        self.addmat.setShortcut(_translate("MainWindow", "Alt+M"))
        self.clearmat.setText(_translate("MainWindow", "CLEAR"))
        self.delmat.setText(_translate("MainWindow", "DEL"))
        self.delmat.setShortcut(_translate("MainWindow", "Backspace, Del"))
        self.label_credits.setText(_translate("MainWindow", "Ruby Raytracer GUI by Tom F."))
        self.label_status.setText(_translate("MainWindow", "Rendering"))
